# Dependencies
markdown:            kramdown
highlighter:         rouge


# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Yixuan
tagline:             '厨娘界元老, 书呆界新人.'
description:         '尘世间一只迷途小书虫.'
url:                 http://yixuan.li
baseurl:             /
paginate:            7

# About/contact
author:
  name:              Yixuan Li
  url:               https://www.macundexiatian.com
  email:             liyixuan5402@gmail.com

# Custom vers
version:             3.0

# Social Media
github:				https://github.com/YixuanFranco
twitter:			https://twitter.com/Yixuan5402

# Theme Author (Please don't edit this line cause of MIT LICENSE rules)
theme:
  creator:			Yixuan Li
  codename:			Geek-green
  link:         https://github.com/YixuanFranco
